name: stage-prod-deployment
on:
  release:
    types: [published]  # Triggers when a new release is created
  # create:
  #   tags: "*"  # Triggers when a new tag is created
permissions:
  id-token: write
  contents: read
jobs:
  stage-deploy:
    name: Deploy to stage
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract version tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Print release information
        run: |
          echo "A new release was created!"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release body: ${{ github.event.release.body }}"

      
  prod-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: stage-deploy
    environment:
      name: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract version tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Print release information
        run: |
          echo "A new release was created!"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release body: ${{ github.event.release.body }}"
